GET http://localhost:3000/


POST http://localhost:3000/mail

Content-Type: application/json
    
    {
        "to": "tcanjb@gmail.com",
        "subject": "Hello",
        "body": {


           
          "name" : "Hello,",
           "contact": "This is a test email.",
          "email":  "Regards,",
           "message" :"Test"
        }
    }